// Mock data — TOÀN BỘ là dữ liệu minh họa (is_demo: true). Backend thật sẽ thay thế file này.
window.DS_ARTIFACTS = [
  { id: 'DS-001', title: 'Bình gốm men ngọc, băng cánh sen', title_en: 'Celadon jar with incised lotus band', shape: 'jar', matKey: 'celadon', type: 'Bình', material: 'Gốm men ngọc', period: 'Trần', dating: 'Khoảng thế kỷ XIII–XIV', dims: 'Cao ≈ 28,4 cm', technique: 'Vuốt tay, khắc chìm dưới men', surface: 'Rạn men tự nhiên, men đọng ở chân', origin: 'Vùng văn hóa Bắc Bộ (minh họa)', status: 'Đang thẩm định', price: '120 tỷ VND', desc: 'Bình dáng thuôn, vai nở, men ngọc phủ toàn thân với băng cánh sen khắc chìm quanh vai.', story: 'Mô típ cánh sen gắn với mỹ thuật Phật giáo thời Lý–Trần, xuất hiện trên cả kiến trúc và đồ tự khí.', sources: ['Hồ sơ hiện vật DS-001 (demo)', 'Tư liệu đối chiếu (demo)'], related: ['DS-007', 'DS-009', 'DS-004'] },
  { id: 'DS-002', title: 'Bát men trắng ngà, lòng ve', title_en: 'Ivory-white glazed bowl', shape: 'bowl', matKey: 'white', type: 'Bát', material: 'Gốm men trắng', period: 'Lý', dating: 'Khoảng thế kỷ XI–XII', dims: 'ĐK miệng ≈ 17,2 cm', technique: 'Vuốt bàn xoay, ve lòng', surface: 'Men trắng ngà, rạn nhẹ', origin: 'Vùng văn hóa Bắc Bộ (minh họa)', status: 'Đã số hóa', price: '45 tỷ VND', desc: 'Bát chân cao, miệng loe nhẹ, men trắng ngà phủ đều, lòng ve một vòng.', story: 'Dòng men trắng ngà thanh nhã thường được gắn với thẩm mỹ cung đình và Phật giáo thời Lý.', sources: ['Hồ sơ hiện vật DS-002 (demo)'], related: ['DS-001', 'DS-007'] },
  { id: 'DS-003', title: 'Đĩa hoa lam, đề tài phong cảnh', title_en: 'Blue-and-white dish, landscape motif', shape: 'plate', matKey: 'hoalam', type: 'Đĩa', material: 'Gốm hoa lam', period: 'Lê sơ', dating: 'Khoảng thế kỷ XV', dims: 'ĐK ≈ 34,5 cm', technique: 'Vẽ lam dưới men', surface: 'Men bóng, lam đậm nhạt có lớp', origin: 'Dòng gốm thương mại (minh họa)', status: 'Đang thẩm định', price: '240 tỷ VND', desc: 'Đĩa lớn vẽ lam đề tài phong cảnh, kiểu thức gắn với dòng gốm thương mại thế kỷ XV.', story: 'Gốm hoa lam Việt thế kỷ XV từng theo thuyền buôn tới nhiều vùng Đông Nam Á và Trung Đông.', sources: ['Hồ sơ hiện vật DS-003 (demo)', 'Tư liệu đối chiếu (demo)'], related: ['DS-010', 'DS-001'] },
  { id: 'DS-004', title: 'Ấm men nâu, quai chạm nổi', title_en: 'Brown-glazed ewer with relief handle', shape: 'am', matKey: 'brown', type: 'Ấm', material: 'Gốm men nâu', period: 'Trần', dating: 'Khoảng thế kỷ XIII–XIV', dims: 'Cao ≈ 19,6 cm', technique: 'Đắp nổi, phủ men nâu', surface: 'Men nâu sậm, vệt chảy tự nhiên', origin: 'Vùng văn hóa Bắc Bộ (minh họa)', status: 'Chưa kiểm chứng', price: '28 tỷ VND', desc: 'Ấm thân tròn, vòi ngắn, quai chạm nổi, men nâu sậm đặc trưng của dòng hoa nâu.', story: 'Dòng men nâu — hoa nâu thời Trần được xem là khỏe khoắn, phóng khoáng, giàu chất dân gian.', sources: ['Thông tin chủ sở hữu (demo)'], related: ['DS-001', 'DS-009'] },
  { id: 'DS-005', title: 'Tượng nghê đất nung', title_en: 'Terracotta nghê figure', shape: 'tuong', matKey: 'terra', type: 'Tượng', material: 'Đất nung', period: 'Lê Trung Hưng', dating: 'Khoảng thế kỷ XVII', dims: 'Cao ≈ 24,0 cm', technique: 'Nặn tay, nung thấp', surface: 'Đất nung đỏ, vết mòn thời gian', origin: 'Kiến trúc đình làng (minh họa)', status: 'Chưa kiểm chứng', price: '12 tỷ VND', desc: 'Tượng nghê phong cách dân gian, khối đơn giản, biểu cảm sống động.', story: 'Nghê là linh vật thuần Việt, thường trấn giữ đình chùa và cổng làng.', sources: ['Thông tin chủ sở hữu (demo)'], related: ['DS-006', 'DS-011'] },
  { id: 'DS-006', title: 'Lư hương sành, tai rồng cách điệu', title_en: 'Stoneware incense burner', shape: 'lu', matKey: 'sanh', type: 'Đồ thờ', material: 'Sành', period: 'Mạc', dating: 'Khoảng thế kỷ XVI', dims: 'Cao ≈ 22,8 cm', technique: 'Đắp nổi, nung sành', surface: 'Sành nâu xám, đanh mặt', origin: 'Đồ tự khí (minh họa)', status: 'Đang thẩm định', price: '78 tỷ VND', desc: 'Lư hương ba chân, tai rồng cách điệu, phong cách đắp nổi thời Mạc.', story: 'Nhiều lư hương thời Mạc mang minh văn ghi năm chế tác và người cung tiến — nguồn sử liệu quý.', sources: ['Hồ sơ hiện vật DS-006 (demo)'], related: ['DS-011', 'DS-005'] },
  { id: 'DS-007', title: 'Bát men ngọc khắc chìm hoa dây', title_en: 'Celadon bowl, incised scroll', shape: 'bowl', matKey: 'celadon', type: 'Bát', material: 'Gốm men ngọc', period: 'Lý', dating: 'Khoảng thế kỷ XII', dims: 'ĐK miệng ≈ 18,8 cm', technique: 'Khắc chìm dưới men', surface: 'Men ngọc trong, đọng xanh ở lòng', origin: 'Vùng văn hóa Bắc Bộ (minh họa)', status: 'Đã số hóa', price: '95 tỷ VND', desc: 'Bát men ngọc khắc chìm hoa dây mềm mại quanh thành ngoài.', story: 'Hoa dây khắc chìm là một trong những mô típ tiêu biểu của thẩm mỹ Lý.', sources: ['Hồ sơ hiện vật DS-007 (demo)'], related: ['DS-001', 'DS-002'] },
  { id: 'DS-008', title: 'Bình vôi men trắng vẽ nâu', title_en: 'Lime pot, white glaze with brown', shape: 'jar', matKey: 'white', type: 'Đồ gia dụng', material: 'Gốm men trắng', period: 'Lê sơ', dating: 'Khoảng thế kỷ XV', dims: 'Cao ≈ 12,4 cm', technique: 'Vẽ nâu trên men trắng', surface: 'Men trắng ngà, nét nâu mộc', origin: 'Đời sống dân gian (minh họa)', status: 'Chưa kiểm chứng', price: '18 tỷ VND', desc: 'Bình vôi dáng tròn, quai nhỏ, gắn với tục ăn trầu của người Việt.', story: 'Bình vôi hiện diện trong hầu hết gia đình Việt xưa — một hiện vật của đời sống thường nhật.', sources: ['Thông tin chủ sở hữu (demo)'], related: ['DS-012', 'DS-002'] },
  { id: 'DS-009', title: 'Đĩa men ngọc, dấu con kê', title_en: 'Celadon dish with spur marks', shape: 'plate', matKey: 'celadon', type: 'Đĩa', material: 'Gốm men ngọc', period: 'Trần', dating: 'Khoảng thế kỷ XIII–XIV', dims: 'ĐK ≈ 26,0 cm', technique: 'Nung chồng, con kê', surface: 'Dấu con kê trong lòng — dấu vết kỹ thuật lò', origin: 'Vùng văn hóa Bắc Bộ (minh họa)', status: 'Đã số hóa', price: '65 tỷ VND', desc: 'Đĩa men ngọc với dấu con kê — bằng chứng trực tiếp của kỹ thuật nung chồng.', story: 'Dấu con kê giúp nhà nghiên cứu đọc được cách xếp lò của người thợ xưa.', sources: ['Hồ sơ hiện vật DS-009 (demo)'], related: ['DS-001', 'DS-007'] },
  { id: 'DS-010', title: 'Ấm hoa lam, nắp núm sen', title_en: 'Blue-and-white ewer, lotus finial', shape: 'am', matKey: 'hoalam', type: 'Ấm', material: 'Gốm hoa lam', period: 'Lê sơ', dating: 'Khoảng thế kỷ XV', dims: 'Cao ≈ 21,2 cm', technique: 'Vẽ lam dưới men', surface: 'Men bóng, lam tươi', origin: 'Dòng gốm thương mại (minh họa)', status: 'Đang thẩm định', price: '180 tỷ VND', desc: 'Ấm hoa lam nắp núm sen, kiểu thức xuất khẩu thế kỷ XV.', story: 'Núm sen trên nắp ấm là chi tiết Việt hóa duyên dáng trên dòng gốm thương mại.', sources: ['Hồ sơ hiện vật DS-010 (demo)'], related: ['DS-003', 'DS-004'] },
  { id: 'DS-011', title: 'Chân đèn sành nâu', title_en: 'Brown stoneware lamp stand', shape: 'lu', matKey: 'sanh', type: 'Đồ thờ', material: 'Sành', period: 'Mạc', dating: 'Khoảng thế kỷ XVI', dims: 'Cao ≈ 31,5 cm', technique: 'Chuốt, đắp nổi', surface: 'Sành nâu, vết lửa lò', origin: 'Đồ tự khí (minh họa)', status: 'Chưa kiểm chứng', price: '24 tỷ VND', desc: 'Chân đèn sành với các băng trang trí đắp nổi.', story: 'Cặp chân đèn — lư hương là bộ tự khí quen thuộc trên ban thờ Việt.', sources: ['Thông tin chủ sở hữu (demo)'], related: ['DS-006', 'DS-005'] },
  { id: 'DS-012', title: 'Vò sành miệng loe, vai đắp nổi', title_en: 'Stoneware jar with flared mouth', shape: 'jar', matKey: 'sanh', type: 'Đồ gia dụng', material: 'Sành', period: 'Nguyễn', dating: 'Khoảng thế kỷ XIX', dims: 'Cao ≈ 35,0 cm', technique: 'Chuốt tay, nung củi', surface: 'Sành nâu đậm, men tro loang', origin: 'Đời sống dân gian (minh họa)', status: 'Chưa kiểm chứng', price: '15 tỷ VND', desc: 'Vò đựng dáng khỏe, vai đắp nổi băng trang trí giản dị.', story: 'Vò sành theo chân người Việt trong mọi sinh hoạt — đựng gạo, nước, mắm muối.', sources: ['Thông tin chủ sở hữu (demo)'], related: ['DS-008', 'DS-005'] }
];
window.DS_PRICE_NOTES = ['Ước tính minh họa cho bản demo — không phải chứng thư thẩm định.', 'Không thay thế thẩm định chuyên môn.', 'Giá trị thực tế phụ thuộc provenance, tình trạng, kiểm chứng, đối chiếu học thuật và thị trường.'];
window.DS_AI_MOCK = [
  { q: 'Tìm giúp tôi một chiếc bình gốm men ngọc thời Trần', id: 'DS-001', confidence: 'Trung bình',
    answer: 'Trong kho dữ liệu minh họa có một hồ sơ phù hợp: bình gốm men ngọc với băng cánh sen khắc chìm, niên đại ước tính khoảng thế kỷ XIII–XIV (thời Trần). Nhận định dựa trên hình thái, đặc điểm men và mô típ trang trí — hồ sơ đang ở trạng thái thẩm định chuyên môn, chưa phải kết luận cuối cùng.' },
  { q: 'Cho tôi xem một ấm gốm men nâu thời Trần', id: 'DS-004', confidence: 'Thấp — chờ thẩm định',
    answer: 'Tìm thấy một hồ sơ minh họa: ấm men nâu quai chạm nổi, ước tính khoảng thế kỷ XIII–XIV. Lưu ý: hồ sơ này chưa kiểm chứng độc lập — hệ thống hiển thị rõ trạng thái đó thay vì khẳng định.' },
  { q: 'Có đĩa hoa lam thế kỷ XV nào không?', id: 'DS-003', confidence: 'Trung bình',
    answer: 'Có một hồ sơ phù hợp: đĩa hoa lam đề tài phong cảnh, khoảng thế kỷ XV (Lê sơ) — dòng gốm thương mại từng xuất khẩu rộng khắp khu vực. Mọi thông số bên cạnh là dữ liệu minh họa.' }
];
